### ISSUE TITLE
Issues on 32-bit

### ISSUE THREAD

**Issue by p0358** [IcePixelx/silver-bun#2]
1.  Invalid cast: `module.cpp(378,34): error C2440: 'initializing': cannot convert from 'DWORD *' to 'uintptr_t *'`
`module.cpp(378,34): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast`
2.  `module.cpp(447,58): error C3861: '__readgsqword': identifier not found`
These things are x64-only: https://learn.microsoft.com/en-us/cpp/intrinsics/readgsbyte-readgsdword-readgsqword-readgsword?view=msvc-170#requirements

It seems the first one can be just fixed by adding reinterpret_cast. As for the second one, I guess it would make the most sense to for now just don't compile `UnlinkFromPEB` function for 32-bit?

**Comment by p0358** [comment]
The issues above are now resolved, however now I noticed that the function `GetExportedFunction` doesn't work, so I guess I'll keep this open for now still

**Comment by IcePixelx** [comment]
Addressed in 92b3eb1
